Sync to kaa.db changes.
This fixes a bug where a file that changed types (e.g. a zero byte generic
file changed to an audio file after data was added to it) would cause 
SystemError: null argument to internal routine


git-svn-id: svn://svn.freevo.org/kaa/trunk@4102 a8f5125c-1e01-0410-8897-facf34644b8e